---
- name: Delete current version of the SSL vhost (will be recreated by certbot)
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/etc/apache2/sites-enabled/{{ instance_name }}_vhost-le-ssl.conf"
    - "/etc/apache2/sites-available/{{ instance_name }}_vhost-le-ssl.conf"

- name: Update main domain {{ domain }} certificate
  include_tasks: call_certbot.yml
  vars:
    domains:
      - "{{ domain }}"
      - "{{ domain_alias }}"
  when: redirect_domain is not defined or redirect_domain == ''

- name: Update redirect domain {{ redirect_domain }} certificate
  include_tasks: call_certbot.yml
  vars:
    domains:
      - "{{ redirect_domain }}"
      - "{{ redirect_domain_alias }}"
  when: redirect_domain is defined and redirect_domain != ''