---
- name: Install goaccess
  apt:
    name: goaccess

- name: Config for stats vhost
  template:
    src: gbstats_vhost.conf
    dest: /etc/apache2/conf-available/gbstats_{{ instance_name }}.conf

- name: Ensure stats html directory
  file:
    path: "{{ stats_base_dir }}/{{ domain }}"
    state: directory

- name: Reload apache2
  service:
    name: apache2
    state: reloaded

- name: Ensure cache directory
  file:
    path: "{{ log_cache_dir }}/{{ domain }}"
    state: directory

- name: Copy run_goaccess.bash
  template:
    src: run_goaccess.bash
    dest: "{{ log_cache_dir }}/{{ domain }}/run_goaccess.bash"
    mode: 0700

- name: Create cron job for nightly stats update
  cron:
    name: "{{ instance_name }}_nightly_stats_collection"
    hour: "0"
    minute: "20"
    job: "{{ log_cache_dir }}/{{ domain }}/run_goaccess.bash"
