name: gruenes-brett
compose:
  # This includes the Traefik network so we can run multiple websites on the same HTTP port
  - .lando-network.yml
services:
  web:
    type: php:custom
    via: cli
    build_as_root:
      - ln -snf /usr/share/zoneinfo/Europe/Berlin /etc/localtime
      - echo Europe/Berlin > /etc/timezone
      - >
        DEBIAN_FRONTEND=noninteractive
        apt-get update -y && apt-get install -y -o Dpkg::Options::=--force-confdef
        software-properties-common
        python3
        ansible
        iproute2
        mariadb-server
        nano
        php7.4
        php7.4-curl
        php7.4-zip
        keychain
        openssh-server
        sudo
        cron
      - 'echo "www-data ALL=NOPASSWD: ALL" >> /etc/sudoers'
      - mkdir -p /run/sshd /run/mysqld
      - chown mysql:mysql /run/mysqld
      - service mysql start
      - |
        cd ansible
        ansible-playbook -i hosts_myinstance basic_setup.yml
        ansible-playbook -i hosts_myinstance setup_wordpress.yml
    command: /usr/bin/systemctl
    run_as_root:
      - service apache2 start
      - service mysql start
      - service ssh start
      - cd ansible && ansible-playbook -i hosts_myinstance update_theme.yml
    run:
      - eval `keychain --eval --agents ssh`
    ssl: false
    scanner: false
    webroot: .
    overrides:
      labels:
        # Make sure that the domain here matches the domain in hosts_myinstance
        - 'traefik.http.routers.gruenes-brett.rule=Host(`gruenes-brett.lndo.site`)'
        - 'traefik.http.routers.gruenes-brett.tls=false'
        - 'traefik.http.services.gruenes-brett.loadbalancer.server.port=80'
        - 'traefik.http.services.gruenes-brett.loadbalancer.server.scheme=http'
      image: ubuntu:20.04
      ports:
        - '2223:22'    # in case we need to SSH into the container
        - '8889:80'    # HTTP
        - '3307:3306'  # MariaDB - CREATE USER 'root'@'%' IDENTIFIED BY 'root'; GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
