//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GruenesBrett.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GruenesBrett.Properties.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        public static string Account_Abort {
            get {
                return ResourceManager.GetString("Account.Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zuständigkeitsbereich.
        /// </summary>
        public static string Account_AreaOfResponsibility {
            get {
                return ResourceManager.GetString("Account.AreaOfResponsibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dein Account ist gesperrt..
        /// </summary>
        public static string Account_Banned {
            get {
                return ResourceManager.GetString("Account.Banned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;Willkommen!&lt;/h1&gt;&lt;p&gt;Dein Account für das Grüne Brett wurde erfolgreich angelegt. Jetzt musst du nur noch deine &lt;a href=&quot;{0}&quot;&gt;E-Mail-Adresse bestätigen&lt;/a&gt; und von einer Person aus unserem Team freigeschaltet werden. Danach kannst du loslegen!&lt;/p&gt;.
        /// </summary>
        public static string Account_ConfirmAccountEmailBody {
            get {
                return ResourceManager.GetString("Account.ConfirmAccountEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestätige deine E-Mail-Adresse für das Grüne Brett.
        /// </summary>
        public static string Account_ConfirmAccountEmailSubject {
            get {
                return ResourceManager.GetString("Account.ConfirmAccountEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail-Adresse bestätigen.
        /// </summary>
        public static string Account_ConfirmEmail {
            get {
                return ResourceManager.GetString("Account.ConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die E-Mail-Adresse für diesen Account wurde schon bestätigt..
        /// </summary>
        public static string Account_ConfirmEmailAlreadyConfirmed {
            get {
                return ResourceManager.GetString("Account.ConfirmEmailAlreadyConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da hat etwas beim Bestätigen deiner E-Mail-Adresse nicht geklappt..
        /// </summary>
        public static string Account_ConfirmEmailError {
            get {
                return ResourceManager.GetString("Account.ConfirmEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deine E-Mail-Adresse wurde erfolgreich bestätigt. Jetzt muss dein Account nur noch von einer Person aus unserem Team freigeschaltet werden. Du bekommst eine weitere E-Mail, wenn das passiert ist..
        /// </summary>
        public static string Account_ConfirmEmailSuccess {
            get {
                return ResourceManager.GetString("Account.ConfirmEmailSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail noch einmal anfordern.
        /// </summary>
        public static string Account_ConfirmEmailTrigger {
            get {
                return ResourceManager.GetString("Account.ConfirmEmailTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wir haben dir noch eine E-Mail zum Bestätigen deiner E-Mail-Adresse gesendet. Bitte überprüfe auch deinen Spam-Ordner!.
        /// </summary>
        public static string Account_ConfirmEmailTriggerText {
            get {
                return ResourceManager.GetString("Account.ConfirmEmailTriggerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account angelegt.
        /// </summary>
        public static string Account_Created {
            get {
                return ResourceManager.GetString("Account.Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das ist die Seite, auf die du immer nach deiner Anmeldung geleitet wirst..
        /// </summary>
        public static string Account_DefaultPageExplanation {
            get {
                return ResourceManager.GetString("Account.DefaultPageExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wenn du eine Initiative oder einen Verein vertrittst, dann sollte das der Name der Initiative oder des Vereins sein. Der Name ist nicht öffentlich sichtbar..
        /// </summary>
        public static string Account_DisplayNameExplanation {
            get {
                return ResourceManager.GetString("Account.DisplayNameExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorname Nachname.
        /// </summary>
        public static string Account_DisplayNamePlaceholder {
            get {
                return ResourceManager.GetString("Account.DisplayNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da hat etwas nicht geklappt..
        /// </summary>
        public static string Account_EditError {
            get {
                return ResourceManager.GetString("Account.EditError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name ändern.
        /// </summary>
        public static string Account_EditName {
            get {
                return ResourceManager.GetString("Account.EditName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort ändern.
        /// </summary>
        public static string Account_EditPassword {
            get {
                return ResourceManager.GetString("Account.EditPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort geändert.
        /// </summary>
        public static string Account_EditPasswordConfirmation {
            get {
                return ResourceManager.GetString("Account.EditPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Passwort wurde erfolgreich geändert..
        /// </summary>
        public static string Account_EditPasswordConfirmationText {
            get {
                return ResourceManager.GetString("Account.EditPasswordConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die E-Mail-Adresse wird zur Anmeldung und für Benachrichtigungen genutzt. Sie ist nicht öffentlich sichtbar und kann später nicht geändert werden..
        /// </summary>
        public static string Account_EmailExplanation {
            get {
                return ResourceManager.GetString("Account.EmailExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email@example.org.
        /// </summary>
        public static string Account_EmailPlaceholder {
            get {
                return ResourceManager.GetString("Account.EmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail-Einstellungen.
        /// </summary>
        public static string Account_EmailSettings {
            get {
                return ResourceManager.GetString("Account.EmailSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort vergessen.
        /// </summary>
        public static string Account_ForgotPassword {
            get {
                return ResourceManager.GetString("Account.ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail gesendet.
        /// </summary>
        public static string Account_ForgotPasswordConfirmation {
            get {
                return ResourceManager.GetString("Account.ForgotPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du solltest in Kürze eine E-Mail mit einem Link zum Zurücksetzen deines Passworts bekommen..
        /// </summary>
        public static string Account_ForgotPasswordConfirmationText {
            get {
                return ResourceManager.GetString("Account.ForgotPasswordConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du hast dein Passwort vergessen?.
        /// </summary>
        public static string Account_ForgotPasswordHeading {
            get {
                return ResourceManager.GetString("Account.ForgotPasswordHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wenn du dein Passwort vergessen hast, dann kannst du dein &lt;a href=&quot;/account/passwort-vergessen&quot;&gt;Passwort zurücksetzen&lt;/a&gt;..
        /// </summary>
        public static string Account_ForgotPasswordText {
            get {
                return ResourceManager.GetString("Account.ForgotPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du hast zu oft ein falsches Passwort eingegeben. Daher ist dein Account vorübergehend gesperrt. Probiere es in ein paar Minuten noch einmal..
        /// </summary>
        public static string Account_LockedOut {
            get {
                return ResourceManager.GetString("Account.LockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anmelden.
        /// </summary>
        public static string Account_Login {
            get {
                return ResourceManager.GetString("Account.Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Anmeldung hat leider nicht geklappt..
        /// </summary>
        public static string Account_LoginFailed {
            get {
                return ResourceManager.GetString("Account.LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abmelden.
        /// </summary>
        public static string Account_Logout {
            get {
                return ResourceManager.GetString("Account.Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mein Account.
        /// </summary>
        public static string Account_MyAccount {
            get {
                return ResourceManager.GetString("Account.MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;Neuer Nutzer&lt;/h1&gt;&lt;p&gt;Du kannst jetzt den &lt;a href=&quot;{0}&quot;&gt;Nutzer freischalten&lt;/a&gt; oder warten, bis es jemand anderes gemacht hat.&lt;/p&gt;.
        /// </summary>
        public static string Account_NewUserEmailBody {
            get {
                return ResourceManager.GetString("Account.NewUserEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein neuer Nutzer hat sich für das Grüne Brett registriert.
        /// </summary>
        public static string Account_NewUserEmailSubject {
            get {
                return ResourceManager.GetString("Account.NewUserEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du hast noch keinen Account?.
        /// </summary>
        public static string Account_NoAccountYetHeading {
            get {
                return ResourceManager.GetString("Account.NoAccountYetHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wenn du häufiger Veranstaltungen anlegst, dann empfehlen wir dir einen &lt;a href=&quot;/account/registrieren&quot;&gt;Account anzulegen&lt;/a&gt;..
        /// </summary>
        public static string Account_NoAccountYetText {
            get {
                return ResourceManager.GetString("Account.NoAccountYetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die E-Mail-Adresse für deinen Accounts ist noch nicht bestätigt. Klicke dazu in der E-Mail auf den Link zum Bestätigen. Wenn du keine E-Mail bekommen hast, dann kannst du eine &lt;a href=&quot;{0}&quot;&gt;weitere E-Mail anfordern&lt;/a&gt;..
        /// </summary>
        public static string Account_NotConfirmed {
            get {
                return ResourceManager.GetString("Account.NotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonstige Einstellungen.
        /// </summary>
        public static string Account_OtherSettings {
            get {
                return ResourceManager.GetString("Account.OtherSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort zuletzt geändert.
        /// </summary>
        public static string Account_PasswordChanged {
            get {
                return ResourceManager.GetString("Account.PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ******.
        /// </summary>
        public static string Account_PasswortPlaceholder {
            get {
                return ResourceManager.GetString("Account.PasswortPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optionale E-Mails sind zum Beispiel Erinnerungen, wenn ein Account oder eine Veranstaltung auf Freigabe wartet. Notwendige E-Mails, wie zum Beispiel die E-Mail zum Zurücksetzen deines Passworts, senden wir dir in jedem Fall..
        /// </summary>
        public static string Account_ReceiveOptionalEmailsExplanation {
            get {
                return ResourceManager.GetString("Account.ReceiveOptionalEmailsExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du wirst maximal eine E-Mail pro Tag und Veranstaltung bekommen, selbst wenn dieselbe Veranstaltung mehrfach am selben Tag gemeldet wurde..
        /// </summary>
        public static string Account_ReceiveReportingEmailsExplanation {
            get {
                return ResourceManager.GetString("Account.ReceiveReportingEmailsExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account anlegen.
        /// </summary>
        public static string Account_Registration {
            get {
                return ResourceManager.GetString("Account.Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warum sollte ich einen Account anlegen?.
        /// </summary>
        public static string Account_RegistrationBenefitsHeading {
            get {
                return ResourceManager.GetString("Account.RegistrationBenefitsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einen Account anzulegen hat viele Vorteile! Du sparst ein wenig Zeit beim Anlegen von Veranstaltungen, weil du nicht immer aufs Neue deinen Namen und deine E-Mail-Adresse eingeben musst. Außerdem werden deine Veranstaltungen direkt nach dem Anlegen automatisch freigegeben und sind so schneller auf der Seite sichtbar. Und falls dir beim Anlegen mal ein Fehler passiert ist, kann du deine eigenen Veranstaltungen nachträglich bearbeiten..
        /// </summary>
        public static string Account_RegistrationBenefitsText {
            get {
                return ResourceManager.GetString("Account.RegistrationBenefitsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account angelegt.
        /// </summary>
        public static string Account_RegistrationConfirmation {
            get {
                return ResourceManager.GetString("Account.RegistrationConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dein Account wurde erfolgreich angelegt. Du solltest in Kürze eine E-Mail mit weiteren Informationen bekommen..
        /// </summary>
        public static string Account_RegistrationConfirmationText {
            get {
                return ResourceManager.GetString("Account.RegistrationConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dein Account wurde angelegt, aber dabei ist ein Fehler aufgetreten. Jemand wird sich bei dir melden..
        /// </summary>
        public static string Account_RegistrationError {
            get {
                return ResourceManager.GetString("Account.RegistrationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort zurücksetzen.
        /// </summary>
        public static string Account_ResetPassword {
            get {
                return ResourceManager.GetString("Account.ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort wurde zurückgesetzt.
        /// </summary>
        public static string Account_ResetPasswordConfirmation {
            get {
                return ResourceManager.GetString("Account.ResetPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dein Passwort wurde erfolgreich zurückgesetzt. Du kannst dich jetzt &lt;a href=&quot;/account/anmelden&quot;&gt;wieder einloggen&lt;/a&gt;. Willkommen zurück!.
        /// </summary>
        public static string Account_ResetPasswordConfirmationText {
            get {
                return ResourceManager.GetString("Account.ResetPasswordConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;Passwort zurücksetzen&lt;/h1&gt;&lt;p&gt;Du kannst &lt;a href=&quot;{0}&quot;&gt;diesen Link&lt;/a&gt; nutzen, um dein Passwort für das Grüne Brett zurückzusetzen. Falls dir dein Passwort in der Zwischenzeit wieder eingefallen ist, kannst du diese E-Mail ignorieren.&lt;/p&gt;.
        /// </summary>
        public static string Account_ResetPasswordEmailBody {
            get {
                return ResourceManager.GetString("Account.ResetPasswordEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort für das Grüne Brett zurücksetzen.
        /// </summary>
        public static string Account_ResetPasswordEmailSubject {
            get {
                return ResourceManager.GetString("Account.ResetPasswordEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da hat etwas beim Zurücksetzen deines Passworts nicht geklappt..
        /// </summary>
        public static string Account_ResetPasswordError {
            get {
                return ResourceManager.GetString("Account.ResetPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern.
        /// </summary>
        public static string Account_Save {
            get {
                return ResourceManager.GetString("Account.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account-Einstellungen.
        /// </summary>
        public static string Account_Settings {
            get {
                return ResourceManager.GetString("Account.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        public static string Accounts_Abort {
            get {
                return ResourceManager.GetString("Accounts.Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Für den Account wurde bereits ein Passwort vergeben..
        /// </summary>
        public static string Accounts_AlreadyHasPassword {
            get {
                return ResourceManager.GetString("Accounts.AlreadyHasPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;Account freigegeben&lt;/h1&gt;&lt;p&gt;Gute Nachrichten! Dein Account für das Grüne Brett wurde eben freigegeben. Wenn du deine E-Mail-Adresse schon bestätigt hast, dann kannst du dich jetzt &lt;a href=&quot;{0}&quot;&gt;auf der Seite einloggen&lt;/a&gt;.&lt;/p&gt;.
        /// </summary>
        public static string Accounts_ApprovalEmailBody {
            get {
                return ResourceManager.GetString("Accounts.ApprovalEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dein Account für das Grüne Brett wurde freigegeben.
        /// </summary>
        public static string Accounts_ApprovalEmailSubject {
            get {
                return ResourceManager.GetString("Accounts.ApprovalEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account freigeben.
        /// </summary>
        public static string Accounts_Approve {
            get {
                return ResourceManager.GetString("Accounts.Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account sperren.
        /// </summary>
        public static string Accounts_Ban {
            get {
                return ResourceManager.GetString("Accounts.Ban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sperren.
        /// </summary>
        public static string Accounts_BanAction {
            get {
                return ResourceManager.GetString("Accounts.BanAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du kannst nicht deinen eigenen Account sperren oder entsperren..
        /// </summary>
        public static string Accounts_BanOrUnbanYourself {
            get {
                return ResourceManager.GetString("Accounts.BanOrUnbanYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account anlegen.
        /// </summary>
        public static string Accounts_Create {
            get {
                return ResourceManager.GetString("Accounts.Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account angelegt.
        /// </summary>
        public static string Accounts_Created {
            get {
                return ResourceManager.GetString("Accounts.Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es ist ein Fehler beim Anlegen des Accounts aufgetreten..
        /// </summary>
        public static string Accounts_CreateError {
            get {
                return ResourceManager.GetString("Accounts.CreateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account löschen.
        /// </summary>
        public static string Accounts_Delete {
            get {
                return ResourceManager.GetString("Accounts.Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen.
        /// </summary>
        public static string Accounts_DeleteAction {
            get {
                return ResourceManager.GetString("Accounts.DeleteAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du kannst nicht deinen eigenen Account löschen..
        /// </summary>
        public static string Accounts_DeleteYourself {
            get {
                return ResourceManager.GetString("Accounts.DeleteYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts bearbeiten.
        /// </summary>
        public static string Accounts_EditAccounts {
            get {
                return ResourceManager.GetString("Accounts.EditAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zuständigkeit bearbeiten.
        /// </summary>
        public static string Accounts_EditResponsibility {
            get {
                return ResourceManager.GetString("Accounts.EditResponsibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolle bearbeiten.
        /// </summary>
        public static string Accounts_EditRole {
            get {
                return ResourceManager.GetString("Accounts.EditRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du kannst nicht die Rolle deines eigenen Accounts bearbeiten..
        /// </summary>
        public static string Accounts_EditRoleOfYourself {
            get {
                return ResourceManager.GetString("Accounts.EditRoleOfYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letzte Anmeldung.
        /// </summary>
        public static string Accounts_LastLogin {
            get {
                return ResourceManager.GetString("Accounts.LastLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrative Links.
        /// </summary>
        public static string Accounts_Links {
            get {
                return ResourceManager.GetString("Accounts.Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eintrag.
        /// </summary>
        public static string Accounts_Message {
            get {
                return ResourceManager.GetString("Accounts.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort setzen.
        /// </summary>
        public static string Accounts_SetPassword {
            get {
                return ResourceManager.GetString("Accounts.SetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort erfolgreich gesetzt.
        /// </summary>
        public static string Accounts_SetPasswordConfirmation {
            get {
                return ResourceManager.GetString("Accounts.SetPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du hast erfolgreich ein Passwort für deinen Account vergeben und deine E-Mail-Adresse bestätigt. Du kannst dich &lt;a href=&quot;/account/anmelden&quot;&gt;jetzt anmelden&lt;/a&gt; und Veranstaltungen erstellen..
        /// </summary>
        public static string Accounts_SetPasswordConfirmationText {
            get {
                return ResourceManager.GetString("Accounts.SetPasswordConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;Account angelegt&lt;/h1&gt;&lt;p&gt;Für dich wurde ein Account für das Grüne Brett angelegt. Jetzt musst du nur noch &lt;a href=&quot;{0}&quot;&gt;ein Passwort vergeben&lt;/a&gt; und dann kannst du dich anmelden und Veranstaltungen erstellen. Bitte beachte, dass der Link zum Setzen des Passworts nur zwei Wochen gültig ist.&lt;/p&gt;.
        /// </summary>
        public static string Accounts_SetPasswordEmailBody {
            get {
                return ResourceManager.GetString("Accounts.SetPasswordEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account für das Grüne Brett angelegt.
        /// </summary>
        public static string Accounts_SetPasswordEmailSubject {
            get {
                return ResourceManager.GetString("Accounts.SetPasswordEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivitäten ansehen.
        /// </summary>
        public static string Accounts_ShowAuditLog {
            get {
                return ResourceManager.GetString("Accounts.ShowAuditLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeitpunkt.
        /// </summary>
        public static string Accounts_Timestamp {
            get {
                return ResourceManager.GetString("Accounts.Timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account entsperren.
        /// </summary>
        public static string Accounts_Unban {
            get {
                return ResourceManager.GetString("Accounts.Unban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entsperren.
        /// </summary>
        public static string Accounts_UnbanAction {
            get {
                return ResourceManager.GetString("Accounts.UnbanAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account-Einstellungen.
        /// </summary>
        public static string AccountSettings {
            get {
                return ResourceManager.GetString("AccountSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wer wir sind.
        /// </summary>
        public static string Content_AboutUs {
            get {
                return ResourceManager.GetString("Content.AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Eine Gruppe von Menschen, die sich dachte „Für Veranstaltungen im Nachhaltigkeitsbereich brauchen wir sowas wie ein &lt;strong&gt;schwarzes Brett, nur halt in Grün!&lt;/strong&gt;“. Nun sind wir froh, dass das Grüne Brett steht und freuen uns, wenn Du Lust hast, uns zu unterstützen!&lt;/p&gt;
        ///&lt;h2&gt;So kannst du mitmachen&lt;/h2&gt;
        ///&lt;ul&gt;
        ///  &lt;li&gt;&lt;strong&gt;Regelmäßig Veranstaltungen hochladen:&lt;/strong&gt; Das Grüne Brett lebt davon, dass viele Menschen Veranstaltungen eintragen. Deshalb freuen wir uns riesig, wenn Du dies regelmäßg mac [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Content_AboutUsText {
            get {
                return ResourceManager.GetString("Content.AboutUsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verwendung von Cookies.
        /// </summary>
        public static string Content_CookieDeclaration {
            get {
                return ResourceManager.GetString("Content.CookieDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Bei der Nutzung der Webseite werden, wenn technisch notwendig, folgende Cookies gesetzt:&lt;/p&gt;.
        /// </summary>
        public static string Content_CookieDeclarationText {
            get {
                return ResourceManager.GetString("Content.CookieDeclarationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datenschutzerklärung.
        /// </summary>
        public static string Content_DataPrivacyPolicy {
            get {
                return ResourceManager.GetString("Content.DataPrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Content_DataPrivacyPolicyText {
            get {
                return ResourceManager.GetString("Content.DataPrivacyPolicyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diese Maßnahme wird finanziert durch Steuermittel auf der Grundlage des vom Sächsischen Landtag beschlossenen Haushalts. Für die Inhalte der Publikationen ist allein die bezuschusste Institution verantwortlich. Die hier dargestellten Positionen geben nicht zwingend den Standpunkt des Freistaats Sachsen oder des Sächsischen Staatsministeriums für Kultus wieder..
        /// </summary>
        public static string Content_FinancedBy {
            get {
                return ResourceManager.GetString("Content.FinancedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impressum.
        /// </summary>
        public static string Content_Imprint {
            get {
                return ResourceManager.GetString("Content.Imprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Content_ImprintText {
            get {
                return ResourceManager.GetString("Content.ImprintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lizenzen.
        /// </summary>
        public static string Content_Licenses {
            get {
                return ResourceManager.GetString("Content.Licenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Diese Webseite nutzt die folgenden Software-Bibliotheken:&lt;/p&gt;.
        /// </summary>
        public static string Content_LicensesText {
            get {
                return ResourceManager.GetString("Content.LicensesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonstige Links.
        /// </summary>
        public static string Content_Links {
            get {
                return ResourceManager.GetString("Content.Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Grüne Brett ist ein Projekt der BUNDjugend Sachsen..
        /// </summary>
        public static string Content_ProjectBy {
            get {
                return ResourceManager.GetString("Content.ProjectBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einen Fehler melden.
        /// </summary>
        public static string Content_ReportIssue {
            get {
                return ResourceManager.GetString("Content.ReportIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Du hast einen Fehler auf dem Grünen Brett gefunden? Dann würden wir uns freuen, wenn du uns schreibst! Wie du das am besten machen kannst, hängt von der Art des Fehlers ab.&lt;/p&gt;
        ///&lt;h2&gt;Redaktionelle Fehler&lt;/h2&gt;
        ///&lt;p&gt;Wenn du eine Veranstaltung mit falschen Informationen gefunden hast, dann benutze am besten die eingebaute Melde-Funktion. Dazu klickst du auf der Seite der Veranstaltung auf den &quot;Veranstaltung melden&quot;-Button und kannst dort den passenden Grund auswählen. Wenn der Fehler schwieriger zu beschreibe [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Content_ReportIssueText {
            get {
                return ResourceManager.GetString("Content.ReportIssueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nutzungsbedingungen.
        /// </summary>
        public static string Content_TermsOfService {
            get {
                return ResourceManager.GetString("Content.TermsOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Content_TermsOfServiceText {
            get {
                return ResourceManager.GetString("Content.TermsOfServiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auf diese Seite hast du keinen Zugriff..
        /// </summary>
        public static string Error_Error403 {
            get {
                return ResourceManager.GetString("Error.Error403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Seite konnte nicht gefunden werden. Hier kommst du &lt;a href=&quot;/&quot;&gt;zurück zur Startseite&lt;/a&gt;..
        /// </summary>
        public static string Error_Error404 {
            get {
                return ResourceManager.GetString("Error.Error404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es ist ein Fehler aufgetreten. Hier kommst du &lt;a href=&quot;/&quot;&gt;zurück zur Startseite&lt;/a&gt;..
        /// </summary>
        public static string Error_Generic {
            get {
                return ResourceManager.GetString("Error.Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler.
        /// </summary>
        public static string Error_Heading {
            get {
                return ResourceManager.GetString("Error.Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        public static string Event_Abort {
            get {
                return ResourceManager.GetString("Event.Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;Veranstaltung wartet auf Freigabe&lt;/h1&gt;&lt;p&gt;Es wurde eine neue Veranstaltung auf dem Grünen Brett eingetragen und wartet jetzt auf &lt;a href=&quot;{0}&quot;&gt;deine Freigabe&lt;/a&gt;..
        /// </summary>
        public static string Event_ApprovalEmailBody {
            get {
                return ResourceManager.GetString("Event.ApprovalEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eine neue Veranstaltung wartet auf Freigabe.
        /// </summary>
        public static string Event_ApprovalEmailSubject {
            get {
                return ResourceManager.GetString("Event.ApprovalEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veranstaltung freigeben.
        /// </summary>
        public static string Event_Approve {
            get {
                return ResourceManager.GetString("Event.Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;Veranstaltung freigegeben&lt;/h1&gt;&lt;p&gt;Gute Neuigkeiten! &lt;a href=&quot;{0}&quot;&gt;Deine Veranstaltung&lt;/a&gt; wurde von unseren Redakteuren für gut befunden und ist jetzt auf dem Grünen Brett sichtbar. Danke für deine Hilfe!&lt;/p&gt;.
        /// </summary>
        public static string Event_ApprovedEmailBody {
            get {
                return ResourceManager.GetString("Event.ApprovedEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deine Veranstaltung wurde freigegeben.
        /// </summary>
        public static string Event_ApprovedEmailSubject {
            get {
                return ResourceManager.GetString("Event.ApprovedEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eine Veranstaltung kann mehreren Kategorien zugeordnet werden..
        /// </summary>
        public static string Event_CategoryExplanation {
            get {
                return ResourceManager.GetString("Event.CategoryExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ich bestätige, die notwendigen Rechte am hochgeladenen Bild zu besitzen und dass damit keine Rechte Dritter verletzt werden..
        /// </summary>
        public static string Event_ConfirmImageRights {
            get {
                return ResourceManager.GetString("Event.ConfirmImageRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ich stimme zu, dass meine eingegebenen Daten, wie in der &lt;a href=&quot;/inhalte/datenschutz&quot; target=&quot;_blank&quot;&gt;Datenschutzerklärung&lt;/a&gt; vom Grünen Brett beschrieben, gesammelt und verarbeitet werden dürfen..
        /// </summary>
        public static string Event_ConfirmPrivacyPolicy {
            get {
                return ResourceManager.GetString("Event.ConfirmPrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veranstaltung angelegt.
        /// </summary>
        public static string Event_CreateConfirmation {
            get {
                return ResourceManager.GetString("Event.CreateConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Die Veranstaltung wurde erfolgreich angelegt. Wenn du möchtest, kannst du noch &lt;a href=&quot;/veranstaltung/anlegen&quot;&gt;eine weitere Veranstaltung anlegen&lt;/a&gt;..
        /// </summary>
        public static string Event_CreateConfirmationText {
            get {
                return ResourceManager.GetString("Event.CreateConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstellt am.
        /// </summary>
        public static string Event_Created {
            get {
                return ResourceManager.GetString("Event.Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstellt von.
        /// </summary>
        public static string Event_CreatedBy {
            get {
                return ResourceManager.GetString("Event.CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deine E-Mail-Adresse nutzen wir nur dafür, dass du deine eigene Veranstaltung später noch bearbeiten kannst oder wenn wir Kontakt zu dir aufnehmen wollen. Sie wird nicht veröffentlicht..
        /// </summary>
        public static string Event_CreatedByEmailExplanation {
            get {
                return ResourceManager.GetString("Event.CreatedByEmailExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email@example.org.
        /// </summary>
        public static string Event_CreatedByEmailPlaceholder {
            get {
                return ResourceManager.GetString("Event.CreatedByEmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deinen Namen nutzen wir nur für den Kontakt mit dir, wenn wir Rückfragen zur Veranstaltung haben. Er wird nicht veröffentlicht..
        /// </summary>
        public static string Event_CreatedByNameExplanation {
            get {
                return ResourceManager.GetString("Event.CreatedByNameExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Event_CreatedByNamePlaceholder {
            get {
                return ResourceManager.GetString("Event.CreatedByNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es ist ein Fehler beim Anlegen der Veranstaltung aufgetreten..
        /// </summary>
        public static string Event_CreateError {
            get {
                return ResourceManager.GetString("Event.CreateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Findet die Veranstaltung nur an einem Tag statt, dann kannst du das Enddatum leer lassen..
        /// </summary>
        public static string Event_DateExplanation {
            get {
                return ResourceManager.GetString("Event.DateExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TT.MM.JJJJ.
        /// </summary>
        public static string Event_DatePlaceholder {
            get {
                return ResourceManager.GetString("Event.DatePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veranstaltung löschen.
        /// </summary>
        public static string Event_Delete {
            get {
                return ResourceManager.GetString("Event.Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veranstaltung bearbeiten.
        /// </summary>
        public static string Event_Edit {
            get {
                return ResourceManager.GetString("Event.Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es ist ein Fehler beim Bearbeiten der Veranstaltung aufgetreten..
        /// </summary>
        public static string Event_EditError {
            get {
                return ResourceManager.GetString("Event.EditError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Beschreibung sollte alle wichtigen Informationen enthalten, die man für eine Teilnahme benötigt (zum Beispiel ob eine Anmeldung nötig ist oder ob die Teilnahme etwas kostet). Links zu Webseiten und E-Mail-Adressen werden nach dem Anlegen der Veranstaltung automatisch anklickbar gemacht..
        /// </summary>
        public static string Event_EventDescriptionExplanation {
            get {
                return ResourceManager.GetString("Event.EventDescriptionExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        public static string Event_EventDescriptionPlaceholder {
            get {
                return ResourceManager.GetString("Event.EventDescriptionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Bild wird im Format 16:9 angezeigt werden und die empfohlene Auflösung beträgt 960x540 Pixel. Die maximale Bildgröße beträgt 10 MB und das Bild muss im JPEG- oder im PNG-Format sein..
        /// </summary>
        public static string Event_EventImageExplanation {
            get {
                return ResourceManager.GetString("Event.EventImageExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das ist der Link zur offiziellen Webseite der Veranstaltung, wenn es eine gibt..
        /// </summary>
        public static string Event_EventLinkExplanation {
            get {
                return ResourceManager.GetString("Event.EventLinkExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://....
        /// </summary>
        public static string Event_EventLinkPlaceholder {
            get {
                return ResourceManager.GetString("Event.EventLinkPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Name sollte, wenn möglich, nicht länger als 70 Zeichen sein..
        /// </summary>
        public static string Event_EventNameExplanation {
            get {
                return ResourceManager.GetString("Event.EventNameExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinigung der Elbwiesen.
        /// </summary>
        public static string Event_EventNamePlaceholder {
            get {
                return ResourceManager.GetString("Event.EventNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informationen.
        /// </summary>
        public static string Event_Information {
            get {
                return ResourceManager.GetString("Event.Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Datum darf nicht in der Vergangenheit liegen..
        /// </summary>
        public static string Event_InvalidDate {
            get {
                return ResourceManager.GetString("Event.InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Enddatum muss nach dem Startdatum liegen..
        /// </summary>
        public static string Event_InvalidDates {
            get {
                return ResourceManager.GetString("Event.InvalidDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Veranstaltung darf maximal {0} Tage lang sein. Trage lieber konkrete Veranstaltungen ein (also zum Beispiel einzelne Workshops oder Vorträge auf einem Festival oder die Vernissage bei einer Ausstellung)..
        /// </summary>
        public static string Event_InvalidEventLength {
            get {
                return ResourceManager.GetString("Event.InvalidEventLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Bild muss ein JPG- oder ein PNG-Bild sein und darf nicht größer als 10 MB sein..
        /// </summary>
        public static string Event_InvalidImage {
            get {
                return ResourceManager.GetString("Event.InvalidImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du musst bestätigen, die Rechte am hochgeladenen Bild zu besitzen..
        /// </summary>
        public static string Event_InvalidImageRights {
            get {
                return ResourceManager.GetString("Event.InvalidImageRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Link muss eine gültige Adresse haben (und zum Beispiel mit http:// oder https:// starten)..
        /// </summary>
        public static string Event_InvalidLink {
            get {
                return ResourceManager.GetString("Event.InvalidLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diese Angabe ist nur relevant für mehrtägige Veranstaltungen. Sie entscheidet darüber, ob die Veranstaltung für jeden Tag oder nur für das Startdatum im Kalender angezeigt wird..
        /// </summary>
        public static string Event_JoinEveryDayExplanation {
            get {
                return ResourceManager.GetString("Event.JoinEveryDayExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wenn die Veranstaltung keine genaue Adresse hat, dann kannst du das Feld leer lassen..
        /// </summary>
        public static string Event_LocationAddressExplanation {
            get {
                return ResourceManager.GetString("Event.LocationAddressExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An der schönen Aue 1.
        /// </summary>
        public static string Event_LocationAddressPlaceholder {
            get {
                return ResourceManager.GetString("Event.LocationAddressPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bei Online-Veranstaltungen kannst du hier den Namen der verwendeten Software eintragen..
        /// </summary>
        public static string Event_LocationNameExplanation {
            get {
                return ResourceManager.GetString("Event.LocationNameExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elbwiesen.
        /// </summary>
        public static string Event_LocationNamePlaceholder {
            get {
                return ResourceManager.GetString("Event.LocationNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to angemeldet.
        /// </summary>
        public static string Event_LoggedIn {
            get {
                return ResourceManager.GetString("Event.LoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du hast einen Account?.
        /// </summary>
        public static string Event_LoginHeading {
            get {
                return ResourceManager.GetString("Event.LoginHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dann solltest du dich &lt;a href=&quot;/account/anmelden?ReturnUrl=%2Fveranstaltung%2Fanlegen&quot;&gt;jetzt anmelden&lt;/a&gt;, damit die Veranstaltung mit deinem Account verknüpft und sofort freigeschaltet wird..
        /// </summary>
        public static string Event_LoginText {
            get {
                return ResourceManager.GetString("Event.LoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mehr Informationen.
        /// </summary>
        public static string Event_MoreInformation {
            get {
                return ResourceManager.GetString("Event.MoreInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name der Veranstaltung.
        /// </summary>
        public static string Event_Name {
            get {
                return ResourceManager.GetString("Event.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Veranstaltung ist noch nicht freigegeben und damit nicht öffentlich sichtbar..
        /// </summary>
        public static string Event_NotApprovedYet {
            get {
                return ResourceManager.GetString("Event.NotApprovedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nicht angemeldet.
        /// </summary>
        public static string Event_NotLoggedIn {
            get {
                return ResourceManager.GetString("Event.NotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das ist der Name der Person oder der Initiative, welche die Veranstaltung organisiert..
        /// </summary>
        public static string Event_OrganizerNameExplanation {
            get {
                return ResourceManager.GetString("Event.OrganizerNameExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsere Stadt soll schöner werden e.V..
        /// </summary>
        public static string Event_OrganizerNamePlaceholder {
            get {
                return ResourceManager.GetString("Event.OrganizerNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veranstaltung ablehnen.
        /// </summary>
        public static string Event_Reject {
            get {
                return ResourceManager.GetString("Event.Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abgelehnt.
        /// </summary>
        public static string Event_Rejected {
            get {
                return ResourceManager.GetString("Event.Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;Veranstaltung abgelehnt&lt;/h1&gt;&lt;p&gt;Leider wurde deine Veranstaltung mit dem Namen &quot;{0}&quot; von unseren Redakteuren abgelehnt. Das bedeutet, dass sie nicht öffentlich auf dem Grünen Brett erscheinen wird. Das kann verschiedene Gründe haben. Vielleicht passt sie nicht so gut zum Grünen Brett oder vielleicht gibt es diese Veranstaltung schon auf der Seite. Vergewissere dich bitte, dass die Veranstaltung unseren Kriterien entspricht und nicht bereits eingetragen wurde, wenn du das nächste Mal eine Veranstaltung ei [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Event_RejectedEmailBody {
            get {
                return ResourceManager.GetString("Event.RejectedEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deine Veranstaltung wurde abgelehnt.
        /// </summary>
        public static string Event_RejectedEmailSubject {
            get {
                return ResourceManager.GetString("Event.RejectedEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veranstaltung melden.
        /// </summary>
        public static string Event_Report {
            get {
                return ResourceManager.GetString("Event.Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veranstaltung gemeldet.
        /// </summary>
        public static string Event_ReportConfirmation {
            get {
                return ResourceManager.GetString("Event.ReportConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Die Veranstaltung wurde unserem Team gemeldet. Wir werden die Veranstaltung prüfen und gegebenenfalls löschen. Vielen Dank für deine Hilfe!&lt;/p&gt;.
        /// </summary>
        public static string Event_ReportConfirmationText {
            get {
                return ResourceManager.GetString("Event.ReportConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Veranstaltung passt nicht zum Grünen Brett..
        /// </summary>
        public static string Event_ReportDoesNotFitSite {
            get {
                return ResourceManager.GetString("Event.ReportDoesNotFitSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;Veranstaltung gemeldet&lt;/h1&gt;&lt;p&gt;Eine Person hat &lt;a href=&quot;{0}&quot;&gt;diese Veranstaltung&lt;/a&gt; auf dem Grünen Brett aus folgendem Grund gemeldet:&lt;/p&gt;&lt;p&gt;{1}&lt;/p&gt;.
        /// </summary>
        public static string Event_ReportEmailBody {
            get {
                return ResourceManager.GetString("Event.ReportEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eine Veranstaltung wurde gemeldet.
        /// </summary>
        public static string Event_ReportEmailSubject {
            get {
                return ResourceManager.GetString("Event.ReportEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Veranstaltung wurde abgesagt..
        /// </summary>
        public static string Event_ReportIsCanceled {
            get {
                return ResourceManager.GetString("Event.ReportIsCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Veranstaltung ist verboten oder ruft zu Straftaten auf..
        /// </summary>
        public static string Event_ReportIsIllegal {
            get {
                return ResourceManager.GetString("Event.ReportIsIllegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Veranstaltung ist nicht öffentlich..
        /// </summary>
        public static string Event_ReportIsNotPublic {
            get {
                return ResourceManager.GetString("Event.ReportIsNotPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Veranstaltung passt aus einem anderen Grund nicht..
        /// </summary>
        public static string Event_ReportIsOther {
            get {
                return ResourceManager.GetString("Event.ReportIsOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Veranstaltung ist Spam oder ein Betrug..
        /// </summary>
        public static string Event_ReportIsSpam {
            get {
                return ResourceManager.GetString("Event.ReportIsSpam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein paar Hinweise.
        /// </summary>
        public static string Event_RulesHeading {
            get {
                return ResourceManager.GetString("Event.RulesHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Du hast eine Veranstaltung, die im Kalender veröffentlicht werden soll? Super!&lt;/p&gt;
        ///&lt;p&gt;Bevor Du den Termin erstellst, vergewissere Dich bitte, dass die Veranstaltung zum Grünen Brett passt.&lt;/p&gt;
        ///&lt;p&gt;Die Veranstaltung…&lt;/p&gt;
        ///&lt;ul&gt;
        ///&lt;li&gt;nimmt Bezug zu Ökologie, Umweltschutz, Klimaschutz oder Nachhaltigkeit&lt;/li&gt;
        ///&lt;li&gt;hat keinen kommerziellen Charakter&lt;/li&gt;
        ///&lt;li&gt;ist für alle zugänglich&lt;/li&gt;
        ///&lt;li&gt;enthält keine parteipolitische Werbung im Veranstaltungsnamen oder im Veranstaltungsbild&lt;/li&gt;
        ///&lt;li&gt;hat einen eindeuti [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Event_RulesText {
            get {
                return ResourceManager.GetString("Event.RulesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veranstaltung teilen.
        /// </summary>
        public static string Event_Share {
            get {
                return ResourceManager.GetString("Event.Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wenn es eine ganztägige Veranstaltung ist, dann kannst du die Uhrzeiten leer lassen..
        /// </summary>
        public static string Event_TimeExplanation {
            get {
                return ResourceManager.GetString("Event.TimeExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --:--.
        /// </summary>
        public static string Event_TimePlaceholder {
            get {
                return ResourceManager.GetString("Event.TimePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Veranstaltung wurde abgelehnt und ist damit nicht öffentlich sichtbar..
        /// </summary>
        public static string Event_WasRejected {
            get {
                return ResourceManager.GetString("Event.WasRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktionen.
        /// </summary>
        public static string Events_Actions {
            get {
                return ResourceManager.GetString("Events.Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Wir haben keine Veranstaltungen für den gewählten Ort und die gewählten Kategorien gefunden. Passe die Filter an, um mehr Veranstaltungen zu finden.&lt;/p&gt;.
        /// </summary>
        public static string Events_AdjustFilters {
            get {
                return ResourceManager.GetString("Events.AdjustFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter anwenden.
        /// </summary>
        public static string Events_ApplyFilters {
            get {
                return ResourceManager.GetString("Events.ApplyFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freigeben.
        /// </summary>
        public static string Events_Approve {
            get {
                return ResourceManager.GetString("Events.Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freigegeben.
        /// </summary>
        public static string Events_Approved {
            get {
                return ResourceManager.GetString("Events.Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorien.
        /// </summary>
        public static string Events_Categories {
            get {
                return ResourceManager.GetString("Events.Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ändern.
        /// </summary>
        public static string Events_ChangeLocation {
            get {
                return ResourceManager.GetString("Events.ChangeLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstellt am.
        /// </summary>
        public static string Events_Created {
            get {
                return ResourceManager.GetString("Events.Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstellt von.
        /// </summary>
        public static string Events_CreatedBy {
            get {
                return ResourceManager.GetString("Events.CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen.
        /// </summary>
        public static string Events_Delete {
            get {
                return ResourceManager.GetString("Events.Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veranstaltungen bearbeiten.
        /// </summary>
        public static string Events_Edit {
            get {
                return ResourceManager.GetString("Events.Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearbeiten.
        /// </summary>
        public static string Events_EditAction {
            get {
                return ResourceManager.GetString("Events.EditAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Events_Filter {
            get {
                return ResourceManager.GetString("Events.Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrative Links.
        /// </summary>
        public static string Events_Links {
            get {
                return ResourceManager.GetString("Events.Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 km.
        /// </summary>
        public static string Events_Local {
            get {
                return ResourceManager.GetString("Events.Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ort:.
        /// </summary>
        public static string Events_Location {
            get {
                return ResourceManager.GetString("Events.Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to angemeldet.
        /// </summary>
        public static string Events_LoggedIn {
            get {
                return ResourceManager.GetString("Events.LoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eintrag.
        /// </summary>
        public static string Events_Message {
            get {
                return ResourceManager.GetString("Events.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mehr Informationen.
        /// </summary>
        public static string Events_MoreInformation {
            get {
                return ResourceManager.GetString("Events.MoreInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name der Veranstaltung.
        /// </summary>
        public static string Events_Name {
            get {
                return ResourceManager.GetString("Events.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Veranstaltungen gefunden.
        /// </summary>
        public static string Events_NoResults {
            get {
                return ResourceManager.GetString("Events.NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nicht angemeldet.
        /// </summary>
        public static string Events_NotLoggedIn {
            get {
                return ResourceManager.GetString("Events.NotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abgelehnt.
        /// </summary>
        public static string Events_Rejected {
            get {
                return ResourceManager.GetString("Events.Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suchradius:.
        /// </summary>
        public static string Events_SearchDistance {
            get {
                return ResourceManager.GetString("Events.SearchDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivitäten ansehen.
        /// </summary>
        public static string Events_ShowAuditLog {
            get {
                return ResourceManager.GetString("Events.ShowAuditLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Events_Status {
            get {
                return ResourceManager.GetString("Events.Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 150 km.
        /// </summary>
        public static string Events_Supraregional {
            get {
                return ResourceManager.GetString("Events.Supraregional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeitpunkt.
        /// </summary>
        public static string Events_Timestamp {
            get {
                return ResourceManager.GetString("Events.Timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wartet auf Freigabe.
        /// </summary>
        public static string Events_WaitingForApproval {
            get {
                return ResourceManager.GetString("Events.WaitingForApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link zur API-Referenz.
        /// </summary>
        public static string Feeds_ApiLink {
            get {
                return ResourceManager.GetString("Feeds.ApiLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wenn du selbst Software entwickelst und die Veranstaltungen des Grünen Bretts dort nutzen willst, dann empfehlen wir dir unsere REST-API. Eine Implementierung sollte nicht schwierig sein, da über die API nur ohnehin öffentliche Daten abgerufen werden können und wir deshalb bisher auf eine Authentifizierung verzichten können..
        /// </summary>
        public static string Feeds_ApiText {
            get {
                return ResourceManager.GetString("Feeds.ApiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API-Integration (REST).
        /// </summary>
        public static string Feeds_ApiTitle {
            get {
                return ResourceManager.GetString("Feeds.ApiTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link zum Feed.
        /// </summary>
        public static string Feeds_AtomLink {
            get {
                return ResourceManager.GetString("Feeds.AtomLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Wenn du bereits einen Feedreader (wie zum Beispiel &lt;a href=&quot;https://feedly.com/news-reader&quot; target=&quot;_blank&quot;&gt;Feedly&lt;/a&gt; oder &lt;a href=&quot;https://www.inoreader.com/&quot; target=&quot;_blank&quot;&gt;Inoreader&lt;/a&gt;) nutzt, dann empfehlen wir dir diese Variante. Dazu benötigst du die Adresse des Feeds, die hinter folgendem Link hinterlegt ist (und die du per Rechtsklick &quot;Adresse des Links kopieren&quot; oder &quot;Link-Adresse kopieren&quot; bekommst):&lt;/p&gt;.
        /// </summary>
        public static string Feeds_AtomText {
            get {
                return ResourceManager.GetString("Feeds.AtomText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed abonnieren (Atom / RSS).
        /// </summary>
        public static string Feeds_AtomTitle {
            get {
                return ResourceManager.GetString("Feeds.AtomTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link zum Kalender.
        /// </summary>
        public static string Feeds_IcalLink {
            get {
                return ResourceManager.GetString("Feeds.IcalLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Wenn du bereits einen digitalen Kalender (wie zum Beispiel &lt;a href=&quot;https://calendar.google.com/calendar/u/0/r/settings/addbyurl&quot; target=&quot;_blank&quot;&gt;Google Calendar&lt;/a&gt; oder &lt;a href=&quot;https://support.apple.com/de-de/guide/calendar/icl1022/mac&quot; target=&quot;_blank&quot;&gt;Apple Calendar&lt;/a&gt;) nutzt, dann kannst du einfach den Kalender des Grünen Bretts abonnieren. Dazu benötigst du die Adresse, die hinter folgendem Link hinterlegt ist (und die du per Rechtsklick &quot;Adresse des Links kopieren&quot; oder &quot;Link-Adresse kopieren&quot; be [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Feeds_IcalText {
            get {
                return ResourceManager.GetString("Feeds.IcalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalender abonnieren (iCal).
        /// </summary>
        public static string Feeds_IcalTitle {
            get {
                return ResourceManager.GetString("Feeds.IcalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feeds / Abos.
        /// </summary>
        public static string Feeds_Index {
            get {
                return ResourceManager.GetString("Feeds.Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Du möchtest immer über die neuesten Veranstaltungen informiert bleiben ohne regelmäßig das Grüne Brett checken zu müssen? Kein Problem! Hier gibt es ein paar Möglichkeiten, wie du immer auf dem Laufenden bleiben kannst.&lt;/p&gt;
        ///&lt;p&gt;Bitte beachte, dass die Links auf dieser Seite durch die Filter-Funktion beeinflusst werden. Wenn du also nur an Veranstaltungen von bestimmten Kategorien interessiert bist, dann wähle links die entsprechenden Kategorien aus und klicke auf &quot;Filter anwenden&quot;.&lt;/p&gt;.
        /// </summary>
        public static string Feeds_Intro {
            get {
                return ResourceManager.GetString("Feeds.Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startseite.
        /// </summary>
        public static string Homepage_Index {
            get {
                return ResourceManager.GetString("Homepage.Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Das Grüne Brett ist ein Kalender für Veranstaltungen mit Bezug zu Ökologie, Umweltschutz, Klimaschutz oder Nachhaltigkeit. Wähle deine Stadt oder Postleitzahl und erkunde, welche Veranstaltungen demnächst in deiner Nähe stattfinden!&lt;/p&gt;
        ///&lt;p&gt;Bitte beachte, dass beim Nutzen der Webseite gegebenenfalls Cookies in deinem Browser gesetzt werden. Genauere Information dazu findest du in unserer &lt;a href=&quot;/inhalte/datenschutz&quot;&gt;Datenschutzerklärung&lt;/a&gt;.&lt;/p&gt;.
        /// </summary>
        public static string Homepage_Introduction {
            get {
                return ResourceManager.GetString("Homepage.Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein Projekt der.
        /// </summary>
        public static string Homepage_ProjectBy {
            get {
                return ResourceManager.GetString("Homepage.ProjectBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suche nach deiner Stadt oder Postleitzahl.
        /// </summary>
        public static string Homepage_SearchCityOrPostCode {
            get {
                return ResourceManager.GetString("Homepage.SearchCityOrPostCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In welcher Stadt möchtest du suchen?.
        /// </summary>
        public static string Homepage_WhereToSearch {
            get {
                return ResourceManager.GetString("Homepage.WhereToSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        public static string Settings_Abort {
            get {
                return ResourceManager.GetString("Settings.Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account-Einstellungen.
        /// </summary>
        public static string Settings_AccountSettings {
            get {
                return ResourceManager.GetString("Settings.AccountSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktion.
        /// </summary>
        public static string Settings_Action {
            get {
                return ResourceManager.GetString("Settings.Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorie hinzufügen.
        /// </summary>
        public static string Settings_AddCategory {
            get {
                return ResourceManager.GetString("Settings.AddCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen.
        /// </summary>
        public static string Settings_Delete {
            get {
                return ResourceManager.GetString("Settings.Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorie löschen.
        /// </summary>
        public static string Settings_DeleteCategory {
            get {
                return ResourceManager.GetString("Settings.DeleteCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearbeiten.
        /// </summary>
        public static string Settings_Edit {
            get {
                return ResourceManager.GetString("Settings.Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorien bearbeiten.
        /// </summary>
        public static string Settings_EditCategories {
            get {
                return ResourceManager.GetString("Settings.EditCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorie bearbeiten.
        /// </summary>
        public static string Settings_EditCategory {
            get {
                return ResourceManager.GetString("Settings.EditCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen.
        /// </summary>
        public static string Settings_EditSettings {
            get {
                return ResourceManager.GetString("Settings.EditSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text bearbeiten.
        /// </summary>
        public static string Settings_EditText {
            get {
                return ResourceManager.GetString("Settings.EditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texte bearbeiten.
        /// </summary>
        public static string Settings_EditTexts {
            get {
                return ResourceManager.GetString("Settings.EditTexts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail-Einstellungen.
        /// </summary>
        public static string Settings_EmailSettings {
            get {
                return ResourceManager.GetString("Settings.EmailSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veranstaltungs-Einstellungen.
        /// </summary>
        public static string Settings_EventSettings {
            get {
                return ResourceManager.GetString("Settings.EventSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eine kommaseparierte Liste von E-Mail-Adressen, welche niemals E-Mails vom Grünen Brett bekommen. Das betrifft auch notwendige E-Mails..
        /// </summary>
        public static string Settings_GlobalOptOutExplanation {
            get {
                return ResourceManager.GetString("Settings.GlobalOptOutExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Settings_Key {
            get {
                return ResourceManager.GetString("Settings.Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weitere Einstellungen.
        /// </summary>
        public static string Settings_Links {
            get {
                return ResourceManager.GetString("Settings.Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die maximale Anzahl von Tagen, die eine Veranstaltung lang sein darf..
        /// </summary>
        public static string Settings_MaximumEventLengthExplanation {
            get {
                return ResourceManager.GetString("Settings.MaximumEventLengthExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern.
        /// </summary>
        public static string Settings_Save {
            get {
                return ResourceManager.GetString("Settings.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legt fest, ob anonyme Personen sich selbst einen Account anlegen können..
        /// </summary>
        public static string Settings_SelfRegistrationExplanation {
            get {
                return ResourceManager.GetString("Settings.SelfRegistrationExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wert.
        /// </summary>
        public static string Settings_Value {
            get {
                return ResourceManager.GetString("Settings.Value", resourceCulture);
            }
        }
    }
}
