//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GruenesBrett.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("GruenesBrett.Properties.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Account_ConfirmAccountEmailSubject {
            get {
                return ResourceManager.GetString("Account.ConfirmAccountEmailSubject", resourceCulture);
            }
        }
        
        public static string Account_ConfirmEmail {
            get {
                return ResourceManager.GetString("Account.ConfirmEmail", resourceCulture);
            }
        }
        
        public static string Account_ForgotPassword {
            get {
                return ResourceManager.GetString("Account.ForgotPassword", resourceCulture);
            }
        }
        
        public static string Account_ForgotPasswordHeading {
            get {
                return ResourceManager.GetString("Account.ForgotPasswordHeading", resourceCulture);
            }
        }
        
        public static string Account_ForgotPasswordText {
            get {
                return ResourceManager.GetString("Account.ForgotPasswordText", resourceCulture);
            }
        }
        
        public static string Account_Login {
            get {
                return ResourceManager.GetString("Account.Login", resourceCulture);
            }
        }
        
        public static string Account_Registration {
            get {
                return ResourceManager.GetString("Account.Registration", resourceCulture);
            }
        }
        
        public static string Account_RegistrationConfirmation {
            get {
                return ResourceManager.GetString("Account.RegistrationConfirmation", resourceCulture);
            }
        }
        
        public static string Account_RegistrationConfirmationText {
            get {
                return ResourceManager.GetString("Account.RegistrationConfirmationText", resourceCulture);
            }
        }
        
        public static string Account_RegistrationBenefitsHeading {
            get {
                return ResourceManager.GetString("Account.RegistrationBenefitsHeading", resourceCulture);
            }
        }
        
        public static string Account_RegistrationBenefitsText {
            get {
                return ResourceManager.GetString("Account.RegistrationBenefitsText", resourceCulture);
            }
        }
        
        public static string Account_RegistrationError {
            get {
                return ResourceManager.GetString("Account.RegistrationError", resourceCulture);
            }
        }
        
        public static string Account_ResetPassword {
            get {
                return ResourceManager.GetString("Account.ResetPassword", resourceCulture);
            }
        }
        
        public static string Account_ResetPasswordConfirmation {
            get {
                return ResourceManager.GetString("Account.ResetPasswordConfirmation", resourceCulture);
            }
        }
        
        public static string Account_ResetPasswordConfirmationText {
            get {
                return ResourceManager.GetString("Account.ResetPasswordConfirmationText", resourceCulture);
            }
        }
        
        public static string Account_ResetPasswordEmailBody {
            get {
                return ResourceManager.GetString("Account.ResetPasswordEmailBody", resourceCulture);
            }
        }
        
        public static string Account_ResetPasswordEmailSubject {
            get {
                return ResourceManager.GetString("Account.ResetPasswordEmailSubject", resourceCulture);
            }
        }
        
        public static string Account_LockedOut {
            get {
                return ResourceManager.GetString("Account.LockedOut", resourceCulture);
            }
        }
        
        public static string Account_NotConfirmed {
            get {
                return ResourceManager.GetString("Account.NotConfirmed", resourceCulture);
            }
        }
        
        public static string Account_LoginFailed {
            get {
                return ResourceManager.GetString("Account.LoginFailed", resourceCulture);
            }
        }
        
        public static string Account_ConfirmEmailError {
            get {
                return ResourceManager.GetString("Account.ConfirmEmailError", resourceCulture);
            }
        }
        
        public static string Account_ConfirmEmailAlreadyConfirmed {
            get {
                return ResourceManager.GetString("Account.ConfirmEmailAlreadyConfirmed", resourceCulture);
            }
        }
        
        public static string Account_ConfirmEmailSuccess {
            get {
                return ResourceManager.GetString("Account.ConfirmEmailSuccess", resourceCulture);
            }
        }
        
        public static string Account_ResetPasswordError {
            get {
                return ResourceManager.GetString("Account.ResetPasswordError", resourceCulture);
            }
        }
        
        public static string Account_ForgotPasswordConfirmation {
            get {
                return ResourceManager.GetString("Account.ForgotPasswordConfirmation", resourceCulture);
            }
        }
        
        public static string Account_ForgotPasswordConfirmationText {
            get {
                return ResourceManager.GetString("Account.ForgotPasswordConfirmationText", resourceCulture);
            }
        }
        
        public static string Error_Heading {
            get {
                return ResourceManager.GetString("Error.Heading", resourceCulture);
            }
        }
        
        public static string Error_Error404 {
            get {
                return ResourceManager.GetString("Error.Error404", resourceCulture);
            }
        }
        
        public static string Error_Generic {
            get {
                return ResourceManager.GetString("Error.Generic", resourceCulture);
            }
        }
        
        public static string Content_Imprint {
            get {
                return ResourceManager.GetString("Content.Imprint", resourceCulture);
            }
        }
        
        public static string Content_DataPrivacyPolicy {
            get {
                return ResourceManager.GetString("Content.DataPrivacyPolicy", resourceCulture);
            }
        }
        
        public static string Content_Links {
            get {
                return ResourceManager.GetString("Content.Links", resourceCulture);
            }
        }
        
        public static string Content_ImprintText {
            get {
                return ResourceManager.GetString("Content.ImprintText", resourceCulture);
            }
        }
        
        public static string Content_TermsOfService {
            get {
                return ResourceManager.GetString("Content.TermsOfService", resourceCulture);
            }
        }
        
        public static string Content_TermsOfServiceText {
            get {
                return ResourceManager.GetString("Content.TermsOfServiceText", resourceCulture);
            }
        }
        
        public static string Content_DataPrivacyPolicyText {
            get {
                return ResourceManager.GetString("Content.DataPrivacyPolicyText", resourceCulture);
            }
        }
        
        public static string Account_Logout {
            get {
                return ResourceManager.GetString("Account.Logout", resourceCulture);
            }
        }
        
        public static string Events_Edit {
            get {
                return ResourceManager.GetString("Events.Edit", resourceCulture);
            }
        }
        
        public static string Account_MyAccount {
            get {
                return ResourceManager.GetString("Account.MyAccount", resourceCulture);
            }
        }
        
        public static string Account_EditPassword {
            get {
                return ResourceManager.GetString("Account.EditPassword", resourceCulture);
            }
        }
        
        public static string Account_EditName {
            get {
                return ResourceManager.GetString("Account.EditName", resourceCulture);
            }
        }
        
        public static string Account_Created {
            get {
                return ResourceManager.GetString("Account.Created", resourceCulture);
            }
        }
        
        public static string Account_EditError {
            get {
                return ResourceManager.GetString("Account.EditError", resourceCulture);
            }
        }
        
        public static string Account_PasswordChanged {
            get {
                return ResourceManager.GetString("Account.PasswordChanged", resourceCulture);
            }
        }
        
        public static string Account_EditPasswordConfirmation {
            get {
                return ResourceManager.GetString("Account.EditPasswordConfirmation", resourceCulture);
            }
        }
        
        public static string Account_EditPasswordConfirmationText {
            get {
                return ResourceManager.GetString("Account.EditPasswordConfirmationText", resourceCulture);
            }
        }
        
        public static string Event_Edit {
            get {
                return ResourceManager.GetString("Event.Edit", resourceCulture);
            }
        }
        
        public static string Event_Delete {
            get {
                return ResourceManager.GetString("Event.Delete", resourceCulture);
            }
        }
        
        public static string Account_NoAccountYetHeading {
            get {
                return ResourceManager.GetString("Account.NoAccountYetHeading", resourceCulture);
            }
        }
        
        public static string Account_NoAccountYetText {
            get {
                return ResourceManager.GetString("Account.NoAccountYetText", resourceCulture);
            }
        }
        
        public static string Content_AboutUs {
            get {
                return ResourceManager.GetString("Content.AboutUs", resourceCulture);
            }
        }
        
        public static string Content_AboutUsText {
            get {
                return ResourceManager.GetString("Content.AboutUsText", resourceCulture);
            }
        }
        
        public static string Accounts_EditAccounts {
            get {
                return ResourceManager.GetString("Accounts.EditAccounts", resourceCulture);
            }
        }
        
        public static string Accounts_LastLogin {
            get {
                return ResourceManager.GetString("Accounts.LastLogin", resourceCulture);
            }
        }
        
        public static string Accounts_Links {
            get {
                return ResourceManager.GetString("Accounts.Links", resourceCulture);
            }
        }
        
        public static string Accounts_Create {
            get {
                return ResourceManager.GetString("Accounts.Create", resourceCulture);
            }
        }
        
        public static string Accounts_Approve {
            get {
                return ResourceManager.GetString("Accounts.Approve", resourceCulture);
            }
        }
        
        public static string Accounts_ApprovalEmailSubject {
            get {
                return ResourceManager.GetString("Accounts.ApprovalEmailSubject", resourceCulture);
            }
        }
        
        public static string Accounts_ApprovalEmailBody {
            get {
                return ResourceManager.GetString("Accounts.ApprovalEmailBody", resourceCulture);
            }
        }
        
        public static string Account_Banned {
            get {
                return ResourceManager.GetString("Account.Banned", resourceCulture);
            }
        }
        
        public static string Accounts_Ban {
            get {
                return ResourceManager.GetString("Accounts.Ban", resourceCulture);
            }
        }
        
        public static string Accounts_UnbanAction {
            get {
                return ResourceManager.GetString("Accounts.UnbanAction", resourceCulture);
            }
        }
        
        public static string Accounts_DeleteAction {
            get {
                return ResourceManager.GetString("Accounts.DeleteAction", resourceCulture);
            }
        }
        
        public static string Accounts_BanAction {
            get {
                return ResourceManager.GetString("Accounts.BanAction", resourceCulture);
            }
        }
        
        public static string Accounts_Unban {
            get {
                return ResourceManager.GetString("Accounts.Unban", resourceCulture);
            }
        }
        
        public static string Accounts_Delete {
            get {
                return ResourceManager.GetString("Accounts.Delete", resourceCulture);
            }
        }
        
        public static string Accounts_BanOrUnbanYourself {
            get {
                return ResourceManager.GetString("Accounts.BanOrUnbanYourself", resourceCulture);
            }
        }
        
        public static string Accounts_DeleteYourself {
            get {
                return ResourceManager.GetString("Accounts.DeleteYourself", resourceCulture);
            }
        }
        
        public static string Accounts_EditRole {
            get {
                return ResourceManager.GetString("Accounts.EditRole", resourceCulture);
            }
        }
        
        public static string Accounts_EditRoleOfYourself {
            get {
                return ResourceManager.GetString("Accounts.EditRoleOfYourself", resourceCulture);
            }
        }
        
        public static string Settings_EditSettings {
            get {
                return ResourceManager.GetString("Settings.EditSettings", resourceCulture);
            }
        }
        
        public static string Settings_EditTexts {
            get {
                return ResourceManager.GetString("Settings.EditTexts", resourceCulture);
            }
        }
        
        public static string Settings_EditCategories {
            get {
                return ResourceManager.GetString("Settings.EditCategories", resourceCulture);
            }
        }
        
        public static string Settings_Links {
            get {
                return ResourceManager.GetString("Settings.Links", resourceCulture);
            }
        }
        
        public static string Account_ConfirmEmailTrigger {
            get {
                return ResourceManager.GetString("Account.ConfirmEmailTrigger", resourceCulture);
            }
        }
        
        public static string Account_ConfirmEmailTriggerText {
            get {
                return ResourceManager.GetString("Account.ConfirmEmailTriggerText", resourceCulture);
            }
        }
        
        public static string Account_EmailSettings {
            get {
                return ResourceManager.GetString("Account.EmailSettings", resourceCulture);
            }
        }
        
        public static string Account_ReceiveOptionalEmailsExplanation {
            get {
                return ResourceManager.GetString("Account.ReceiveOptionalEmailsExplanation", resourceCulture);
            }
        }
        
        public static string Account_Save {
            get {
                return ResourceManager.GetString("Account.Save", resourceCulture);
            }
        }
        
        public static string Account_Settings {
            get {
                return ResourceManager.GetString("Account.Settings", resourceCulture);
            }
        }
        
        public static string Account_OtherSettings {
            get {
                return ResourceManager.GetString("Account.OtherSettings", resourceCulture);
            }
        }
        
        public static string Account_ReceiveReportingEmailsExplanation {
            get {
                return ResourceManager.GetString("Account.ReceiveReportingEmailsExplanation", resourceCulture);
            }
        }
        
        public static string Account_DefaultPageExplanation {
            get {
                return ResourceManager.GetString("Account.DefaultPageExplanation", resourceCulture);
            }
        }
        
        public static string Account_NewUserEmailSubject {
            get {
                return ResourceManager.GetString("Account.NewUserEmailSubject", resourceCulture);
            }
        }
        
        public static string Account_NewUserEmailBody {
            get {
                return ResourceManager.GetString("Account.NewUserEmailBody", resourceCulture);
            }
        }
        
        public static string Account_DisplayNameExplanation {
            get {
                return ResourceManager.GetString("Account.DisplayNameExplanation", resourceCulture);
            }
        }
        
        public static string Account_EmailExplanation {
            get {
                return ResourceManager.GetString("Account.EmailExplanation", resourceCulture);
            }
        }
        
        public static string Account_DisplayNamePlaceholder {
            get {
                return ResourceManager.GetString("Account.DisplayNamePlaceholder", resourceCulture);
            }
        }
        
        public static string Account_ConfirmAccountEmailBody {
            get {
                return ResourceManager.GetString("Account.ConfirmAccountEmailBody", resourceCulture);
            }
        }
        
        public static string Account_EmailPlaceholder {
            get {
                return ResourceManager.GetString("Account.EmailPlaceholder", resourceCulture);
            }
        }
        
        public static string Account_PasswortPlaceholder {
            get {
                return ResourceManager.GetString("Account.PasswortPlaceholder", resourceCulture);
            }
        }
        
        public static string Error_Error403 {
            get {
                return ResourceManager.GetString("Error.Error403", resourceCulture);
            }
        }
        
        public static string Settings_GlobalOptOutExplanation {
            get {
                return ResourceManager.GetString("Settings.GlobalOptOutExplanation", resourceCulture);
            }
        }
        
        public static string Settings_Save {
            get {
                return ResourceManager.GetString("Settings.Save", resourceCulture);
            }
        }
        
        public static string Settings_EditText {
            get {
                return ResourceManager.GetString("Settings.EditText", resourceCulture);
            }
        }
        
        public static string Settings_Action {
            get {
                return ResourceManager.GetString("Settings.Action", resourceCulture);
            }
        }
        
        public static string Settings_Key {
            get {
                return ResourceManager.GetString("Settings.Key", resourceCulture);
            }
        }
        
        public static string Settings_Value {
            get {
                return ResourceManager.GetString("Settings.Value", resourceCulture);
            }
        }
        
        public static string Settings_Edit {
            get {
                return ResourceManager.GetString("Settings.Edit", resourceCulture);
            }
        }
        
        public static string Settings_AddCategory {
            get {
                return ResourceManager.GetString("Settings.AddCategory", resourceCulture);
            }
        }
        
        public static string Settings_Delete {
            get {
                return ResourceManager.GetString("Settings.Delete", resourceCulture);
            }
        }
        
        public static string Settings_Abort {
            get {
                return ResourceManager.GetString("Settings.Abort", resourceCulture);
            }
        }
        
        public static string Settings_EditCategory {
            get {
                return ResourceManager.GetString("Settings.EditCategory", resourceCulture);
            }
        }
        
        public static string Settings_DeleteCategory {
            get {
                return ResourceManager.GetString("Settings.DeleteCategory", resourceCulture);
            }
        }
        
        public static string Account_Abort {
            get {
                return ResourceManager.GetString("Account.Abort", resourceCulture);
            }
        }
        
        public static string Accounts_Abort {
            get {
                return ResourceManager.GetString("Accounts.Abort", resourceCulture);
            }
        }
        
        public static string Accounts_CreateError {
            get {
                return ResourceManager.GetString("Accounts.CreateError", resourceCulture);
            }
        }
        
        public static string Accounts_SetPasswordEmailSubject {
            get {
                return ResourceManager.GetString("Accounts.SetPasswordEmailSubject", resourceCulture);
            }
        }
        
        public static string Accounts_SetPasswordEmailBody {
            get {
                return ResourceManager.GetString("Accounts.SetPasswordEmailBody", resourceCulture);
            }
        }
        
        public static string Accounts_AlreadyHasPassword {
            get {
                return ResourceManager.GetString("Accounts.AlreadyHasPassword", resourceCulture);
            }
        }
        
        public static string Accounts_SetPassword {
            get {
                return ResourceManager.GetString("Accounts.SetPassword", resourceCulture);
            }
        }
        
        public static string Accounts_SetPasswordConfirmation {
            get {
                return ResourceManager.GetString("Accounts.SetPasswordConfirmation", resourceCulture);
            }
        }
        
        public static string Accounts_SetPasswordConfirmationText {
            get {
                return ResourceManager.GetString("Accounts.SetPasswordConfirmationText", resourceCulture);
            }
        }
        
        public static string Accounts_ShowAuditLog {
            get {
                return ResourceManager.GetString("Accounts.ShowAuditLog", resourceCulture);
            }
        }
        
        public static string Accounts_Message {
            get {
                return ResourceManager.GetString("Accounts.Message", resourceCulture);
            }
        }
        
        public static string Accounts_Timestamp {
            get {
                return ResourceManager.GetString("Accounts.Timestamp", resourceCulture);
            }
        }
        
        public static string Event_LoginHeading {
            get {
                return ResourceManager.GetString("Event.LoginHeading", resourceCulture);
            }
        }
        
        public static string Event_LoginText {
            get {
                return ResourceManager.GetString("Event.LoginText", resourceCulture);
            }
        }
        
        public static string Event_RulesHeading {
            get {
                return ResourceManager.GetString("Event.RulesHeading", resourceCulture);
            }
        }
        
        public static string Event_RulesText {
            get {
                return ResourceManager.GetString("Event.RulesText", resourceCulture);
            }
        }
        
        public static string Event_CreatedByNamePlaceholder {
            get {
                return ResourceManager.GetString("Event.CreatedByNamePlaceholder", resourceCulture);
            }
        }
        
        public static string Event_CreatedByNameExplanation {
            get {
                return ResourceManager.GetString("Event.CreatedByNameExplanation", resourceCulture);
            }
        }
        
        public static string Event_CreatedByEmailPlaceholder {
            get {
                return ResourceManager.GetString("Event.CreatedByEmailPlaceholder", resourceCulture);
            }
        }
        
        public static string Event_CreatedByEmailExplanation {
            get {
                return ResourceManager.GetString("Event.CreatedByEmailExplanation", resourceCulture);
            }
        }
        
        public static string Event_EventNamePlaceholder {
            get {
                return ResourceManager.GetString("Event.EventNamePlaceholder", resourceCulture);
            }
        }
        
        public static string Event_EventNameExplanation {
            get {
                return ResourceManager.GetString("Event.EventNameExplanation", resourceCulture);
            }
        }
        
        public static string Event_OrganizerNamePlaceholder {
            get {
                return ResourceManager.GetString("Event.OrganizerNamePlaceholder", resourceCulture);
            }
        }
        
        public static string Event_OrganizerNameExplanation {
            get {
                return ResourceManager.GetString("Event.OrganizerNameExplanation", resourceCulture);
            }
        }
        
        public static string Event_EventLinkPlaceholder {
            get {
                return ResourceManager.GetString("Event.EventLinkPlaceholder", resourceCulture);
            }
        }
        
        public static string Event_EventLinkExplanation {
            get {
                return ResourceManager.GetString("Event.EventLinkExplanation", resourceCulture);
            }
        }
        
        public static string Event_DatePlaceholder {
            get {
                return ResourceManager.GetString("Event.DatePlaceholder", resourceCulture);
            }
        }
        
        public static string Event_DateExplanation {
            get {
                return ResourceManager.GetString("Event.DateExplanation", resourceCulture);
            }
        }
        
        public static string Event_TimePlaceholder {
            get {
                return ResourceManager.GetString("Event.TimePlaceholder", resourceCulture);
            }
        }
        
        public static string Event_TimeExplanation {
            get {
                return ResourceManager.GetString("Event.TimeExplanation", resourceCulture);
            }
        }
        
        public static string Event_JoinEveryDayExplanation {
            get {
                return ResourceManager.GetString("Event.JoinEveryDayExplanation", resourceCulture);
            }
        }
        
        public static string Event_LocationNamePlaceholder {
            get {
                return ResourceManager.GetString("Event.LocationNamePlaceholder", resourceCulture);
            }
        }
        
        public static string Event_LocationNameExplanation {
            get {
                return ResourceManager.GetString("Event.LocationNameExplanation", resourceCulture);
            }
        }
        
        public static string Event_LocationAddressPlaceholder {
            get {
                return ResourceManager.GetString("Event.LocationAddressPlaceholder", resourceCulture);
            }
        }
        
        public static string Event_LocationAddressExplanation {
            get {
                return ResourceManager.GetString("Event.LocationAddressExplanation", resourceCulture);
            }
        }
        
        public static string Event_EventDescriptionPlaceholder {
            get {
                return ResourceManager.GetString("Event.EventDescriptionPlaceholder", resourceCulture);
            }
        }
        
        public static string Event_EventDescriptionExplanation {
            get {
                return ResourceManager.GetString("Event.EventDescriptionExplanation", resourceCulture);
            }
        }
        
        public static string Event_CategoryExplanation {
            get {
                return ResourceManager.GetString("Event.CategoryExplanation", resourceCulture);
            }
        }
        
        public static string Event_EventImageExplanation {
            get {
                return ResourceManager.GetString("Event.EventImageExplanation", resourceCulture);
            }
        }
        
        public static string Event_ConfirmImageRights {
            get {
                return ResourceManager.GetString("Event.ConfirmImageRights", resourceCulture);
            }
        }
        
        public static string Event_ConfirmPrivacyPolicy {
            get {
                return ResourceManager.GetString("Event.ConfirmPrivacyPolicy", resourceCulture);
            }
        }
        
        public static string Events_Links {
            get {
                return ResourceManager.GetString("Events.Links", resourceCulture);
            }
        }
        
        public static string Events_ShowAuditLog {
            get {
                return ResourceManager.GetString("Events.ShowAuditLog", resourceCulture);
            }
        }
        
        public static string Events_Message {
            get {
                return ResourceManager.GetString("Events.Message", resourceCulture);
            }
        }
        
        public static string Events_Timestamp {
            get {
                return ResourceManager.GetString("Events.Timestamp", resourceCulture);
            }
        }
        
        public static string Event_CreateConfirmation {
            get {
                return ResourceManager.GetString("Event.CreateConfirmation", resourceCulture);
            }
        }
        
        public static string Event_CreateError {
            get {
                return ResourceManager.GetString("Event.CreateError", resourceCulture);
            }
        }
        
        public static string Event_InvalidImage {
            get {
                return ResourceManager.GetString("Event.InvalidImage", resourceCulture);
            }
        }
        
        public static string Events_MoreInformation {
            get {
                return ResourceManager.GetString("Events.MoreInformation", resourceCulture);
            }
        }
        
        public static string Event_Share {
            get {
                return ResourceManager.GetString("Event.Share", resourceCulture);
            }
        }
        
        public static string Event_Information {
            get {
                return ResourceManager.GetString("Event.Information", resourceCulture);
            }
        }
        
        public static string Event_Report {
            get {
                return ResourceManager.GetString("Event.Report", resourceCulture);
            }
        }
        
        public static string Event_ReportDoesNotFitSite {
            get {
                return ResourceManager.GetString("Event.ReportDoesNotFitSite", resourceCulture);
            }
        }
        
        public static string Event_ReportIsSpam {
            get {
                return ResourceManager.GetString("Event.ReportIsSpam", resourceCulture);
            }
        }
        
        public static string Event_ReportIsCanceled {
            get {
                return ResourceManager.GetString("Event.ReportIsCanceled", resourceCulture);
            }
        }
        
        public static string Event_ReportIsNotPublic {
            get {
                return ResourceManager.GetString("Event.ReportIsNotPublic", resourceCulture);
            }
        }
        
        public static string Event_ReportIsOther {
            get {
                return ResourceManager.GetString("Event.ReportIsOther", resourceCulture);
            }
        }
        
        public static string Event_ReportIsIllegal {
            get {
                return ResourceManager.GetString("Event.ReportIsIllegal", resourceCulture);
            }
        }
        
        public static string Event_Abort {
            get {
                return ResourceManager.GetString("Event.Abort", resourceCulture);
            }
        }
        
        public static string Homepage_Index {
            get {
                return ResourceManager.GetString("Homepage.Index", resourceCulture);
            }
        }
        
        public static string Homepage_Introduction {
            get {
                return ResourceManager.GetString("Homepage.Introduction", resourceCulture);
            }
        }
        
        public static string Homepage_ProjectBy {
            get {
                return ResourceManager.GetString("Homepage.ProjectBy", resourceCulture);
            }
        }
        
        public static string Homepage_SearchCityOrPostCode {
            get {
                return ResourceManager.GetString("Homepage.SearchCityOrPostCode", resourceCulture);
            }
        }
        
        public static string Homepage_WhereToSearch {
            get {
                return ResourceManager.GetString("Homepage.WhereToSearch", resourceCulture);
            }
        }
        
        public static string Events_Filter {
            get {
                return ResourceManager.GetString("Events.Filter", resourceCulture);
            }
        }
        
        public static string Events_Location {
            get {
                return ResourceManager.GetString("Events.Location", resourceCulture);
            }
        }
        
        public static string Events_SearchDistance {
            get {
                return ResourceManager.GetString("Events.SearchDistance", resourceCulture);
            }
        }
        
        public static string Events_ChangeLocation {
            get {
                return ResourceManager.GetString("Events.ChangeLocation", resourceCulture);
            }
        }
        
        public static string Events_Local {
            get {
                return ResourceManager.GetString("Events.Local", resourceCulture);
            }
        }
        
        public static string Events_Supraregional {
            get {
                return ResourceManager.GetString("Events.Supraregional", resourceCulture);
            }
        }
        
        public static string Events_Categories {
            get {
                return ResourceManager.GetString("Events.Categories", resourceCulture);
            }
        }
        
        public static string Events_ApplyFilters {
            get {
                return ResourceManager.GetString("Events.ApplyFilters", resourceCulture);
            }
        }
        
        public static string Events_NoResults {
            get {
                return ResourceManager.GetString("Events.NoResults", resourceCulture);
            }
        }
        
        public static string Events_AdjustFilters {
            get {
                return ResourceManager.GetString("Events.AdjustFilters", resourceCulture);
            }
        }
        
        public static string Events_Created {
            get {
                return ResourceManager.GetString("Events.Created", resourceCulture);
            }
        }
        
        public static string Events_CreatedBy {
            get {
                return ResourceManager.GetString("Events.CreatedBy", resourceCulture);
            }
        }
        
        public static string Events_Name {
            get {
                return ResourceManager.GetString("Events.Name", resourceCulture);
            }
        }
        
        public static string Events_WaitingForApproval {
            get {
                return ResourceManager.GetString("Events.WaitingForApproval", resourceCulture);
            }
        }
        
        public static string Events_Approved {
            get {
                return ResourceManager.GetString("Events.Approved", resourceCulture);
            }
        }
        
        public static string Events_LoggedIn {
            get {
                return ResourceManager.GetString("Events.LoggedIn", resourceCulture);
            }
        }
        
        public static string Events_NotLoggedIn {
            get {
                return ResourceManager.GetString("Events.NotLoggedIn", resourceCulture);
            }
        }
        
        public static string Accounts_EditResponsibility {
            get {
                return ResourceManager.GetString("Accounts.EditResponsibility", resourceCulture);
            }
        }
        
        public static string Account_AreaOfResponsibility {
            get {
                return ResourceManager.GetString("Account.AreaOfResponsibility", resourceCulture);
            }
        }
        
        public static string Events_Actions {
            get {
                return ResourceManager.GetString("Events.Actions", resourceCulture);
            }
        }
        
        public static string Events_Delete {
            get {
                return ResourceManager.GetString("Events.Delete", resourceCulture);
            }
        }
        
        public static string Events_Approve {
            get {
                return ResourceManager.GetString("Events.Approve", resourceCulture);
            }
        }
        
        public static string Event_Approve {
            get {
                return ResourceManager.GetString("Event.Approve", resourceCulture);
            }
        }
        
        public static string Events_EditAction {
            get {
                return ResourceManager.GetString("Events.EditAction", resourceCulture);
            }
        }
        
        public static string Event_ApprovedEmailSubject {
            get {
                return ResourceManager.GetString("Event.ApprovedEmailSubject", resourceCulture);
            }
        }
        
        public static string Event_ApprovedEmailBody {
            get {
                return ResourceManager.GetString("Event.ApprovedEmailBody", resourceCulture);
            }
        }
        
        public static string Event_ApprovalEmailSubject {
            get {
                return ResourceManager.GetString("Event.ApprovalEmailSubject", resourceCulture);
            }
        }
        
        public static string Event_ApprovalEmailBody {
            get {
                return ResourceManager.GetString("Event.ApprovalEmailBody", resourceCulture);
            }
        }
        
        public static string Event_ReportConfirmation {
            get {
                return ResourceManager.GetString("Event.ReportConfirmation", resourceCulture);
            }
        }
        
        public static string Event_ReportEmailSubject {
            get {
                return ResourceManager.GetString("Event.ReportEmailSubject", resourceCulture);
            }
        }
        
        public static string Event_ReportEmailBody {
            get {
                return ResourceManager.GetString("Event.ReportEmailBody", resourceCulture);
            }
        }
        
        public static string Event_ReportConfirmationText {
            get {
                return ResourceManager.GetString("Event.ReportConfirmationText", resourceCulture);
            }
        }
        
        public static string Event_NotApprovedYet {
            get {
                return ResourceManager.GetString("Event.NotApprovedYet", resourceCulture);
            }
        }
        
        public static string Content_ReportIssue {
            get {
                return ResourceManager.GetString("Content.ReportIssue", resourceCulture);
            }
        }
        
        public static string Event_CreateConfirmationText {
            get {
                return ResourceManager.GetString("Event.CreateConfirmationText", resourceCulture);
            }
        }
        
        public static string Event_EditError {
            get {
                return ResourceManager.GetString("Event.EditError", resourceCulture);
            }
        }
        
        public static string Feeds_Index {
            get {
                return ResourceManager.GetString("Feeds.Index", resourceCulture);
            }
        }
        
        public static string Feeds_Intro {
            get {
                return ResourceManager.GetString("Feeds.Intro", resourceCulture);
            }
        }
        
        public static string Feeds_IcalTitle {
            get {
                return ResourceManager.GetString("Feeds.IcalTitle", resourceCulture);
            }
        }
        
        public static string Feeds_AtomTitle {
            get {
                return ResourceManager.GetString("Feeds.AtomTitle", resourceCulture);
            }
        }
        
        public static string Feeds_IcalText {
            get {
                return ResourceManager.GetString("Feeds.IcalText", resourceCulture);
            }
        }
        
        public static string Feeds_AtomText {
            get {
                return ResourceManager.GetString("Feeds.AtomText", resourceCulture);
            }
        }
        
        public static string Feeds_IcalLink {
            get {
                return ResourceManager.GetString("Feeds.IcalLink", resourceCulture);
            }
        }
        
        public static string Feeds_AtomLink {
            get {
                return ResourceManager.GetString("Feeds.AtomLink", resourceCulture);
            }
        }
        
        public static string Content_Licenses {
            get {
                return ResourceManager.GetString("Content.Licenses", resourceCulture);
            }
        }
        
        public static string Content_LicensesText {
            get {
                return ResourceManager.GetString("Content.LicensesText", resourceCulture);
            }
        }
        
        public static string Accounts_Created {
            get {
                return ResourceManager.GetString("Accounts.Created", resourceCulture);
            }
        }
        
        public static string Event_Name {
            get {
                return ResourceManager.GetString("Event.Name", resourceCulture);
            }
        }
        
        public static string Event_Created {
            get {
                return ResourceManager.GetString("Event.Created", resourceCulture);
            }
        }
        
        public static string Event_CreatedBy {
            get {
                return ResourceManager.GetString("Event.CreatedBy", resourceCulture);
            }
        }
        
        public static string Event_LoggedIn {
            get {
                return ResourceManager.GetString("Event.LoggedIn", resourceCulture);
            }
        }
        
        public static string Event_NotLoggedIn {
            get {
                return ResourceManager.GetString("Event.NotLoggedIn", resourceCulture);
            }
        }
        
        public static string Event_MoreInformation {
            get {
                return ResourceManager.GetString("Event.MoreInformation", resourceCulture);
            }
        }
        
        public static string Settings_SelfRegistrationExplanation {
            get {
                return ResourceManager.GetString("Settings.SelfRegistrationExplanation", resourceCulture);
            }
        }
        
        public static string Settings_MaximumEventLengthExplanation {
            get {
                return ResourceManager.GetString("Settings.MaximumEventLengthExplanation", resourceCulture);
            }
        }
        
        public static string Settings_EmailSettings {
            get {
                return ResourceManager.GetString("Settings.EmailSettings", resourceCulture);
            }
        }
        
        public static string Settings_EventSettings {
            get {
                return ResourceManager.GetString("Settings.EventSettings", resourceCulture);
            }
        }
        
        public static string AccountSettings {
            get {
                return ResourceManager.GetString("AccountSettings", resourceCulture);
            }
        }
        
        public static string Settings_AccountSettings {
            get {
                return ResourceManager.GetString("Settings.AccountSettings", resourceCulture);
            }
        }
        
        public static string Event_InvalidEventLength {
            get {
                return ResourceManager.GetString("Event.InvalidEventLength", resourceCulture);
            }
        }
        
        public static string Event_InvalidDate {
            get {
                return ResourceManager.GetString("Event.InvalidDate", resourceCulture);
            }
        }
        
        public static string Event_InvalidDates {
            get {
                return ResourceManager.GetString("Event.InvalidDates", resourceCulture);
            }
        }
        
        public static string Event_InvalidImageRights {
            get {
                return ResourceManager.GetString("Event.InvalidImageRights", resourceCulture);
            }
        }
        
        public static string Event_InvalidLink {
            get {
                return ResourceManager.GetString("Event.InvalidLink", resourceCulture);
            }
        }
        
        public static string Content_CookieDeclaration {
            get {
                return ResourceManager.GetString("Content.CookieDeclaration", resourceCulture);
            }
        }
        
        public static string Content_CookieDeclarationText {
            get {
                return ResourceManager.GetString("Content.CookieDeclarationText", resourceCulture);
            }
        }
        
        public static string Content_ReportIssueText {
            get {
                return ResourceManager.GetString("Content.ReportIssueText", resourceCulture);
            }
        }
        
        public static string Feeds_ApiTitle {
            get {
                return ResourceManager.GetString("Feeds.ApiTitle", resourceCulture);
            }
        }
        
        public static string Feeds_ApiLink {
            get {
                return ResourceManager.GetString("Feeds.ApiLink", resourceCulture);
            }
        }
        
        public static string Feeds_ApiText {
            get {
                return ResourceManager.GetString("Feeds.ApiText", resourceCulture);
            }
        }
        
        public static string Content_ProjectBy {
            get {
                return ResourceManager.GetString("Content.ProjectBy", resourceCulture);
            }
        }
        
        public static string Content_FinancedBy {
            get {
                return ResourceManager.GetString("Content.FinancedBy", resourceCulture);
            }
        }
        
        public static string Event_Reject {
            get {
                return ResourceManager.GetString("Event.Reject", resourceCulture);
            }
        }
        
        public static string Event_RejectedEmailSubject {
            get {
                return ResourceManager.GetString("Event.RejectedEmailSubject", resourceCulture);
            }
        }
        
        public static string Event_RejectedEmailBody {
            get {
                return ResourceManager.GetString("Event.RejectedEmailBody", resourceCulture);
            }
        }
        
        public static string Events_Rejected {
            get {
                return ResourceManager.GetString("Events.Rejected", resourceCulture);
            }
        }
        
        public static string Event_WasRejected {
            get {
                return ResourceManager.GetString("Event.WasRejected", resourceCulture);
            }
        }
        
        public static string Content_Changelog {
            get {
                return ResourceManager.GetString("Content.Changelog", resourceCulture);
            }
        }
        
        public static string Content_ChangelogText {
            get {
                return ResourceManager.GetString("Content.ChangelogText", resourceCulture);
            }
        }
        
        public static string Event_InvalidEndTime {
            get {
                return ResourceManager.GetString("Event.InvalidEndTime", resourceCulture);
            }
        }
        
        public static string Event_InvalidStartTime {
            get {
                return ResourceManager.GetString("Event.InvalidStartTime", resourceCulture);
            }
        }
        
        public static string Event_InThePast {
            get {
                return ResourceManager.GetString("Event.InThePast", resourceCulture);
            }
        }
        
        public static string Accounts_AssigningRoleNotAllowed {
            get {
                return ResourceManager.GetString("Accounts.AssigningRoleNotAllowed", resourceCulture);
            }
        }
        
        public static string Accounts_BanOrUnbanNotAllowed {
            get {
                return ResourceManager.GetString("Accounts.BanOrUnbanNotAllowed", resourceCulture);
            }
        }
        
        public static string Accounts_DeleteNotAllowed {
            get {
                return ResourceManager.GetString("Accounts.DeleteNotAllowed", resourceCulture);
            }
        }
        
        public static string Accounts_EditRoleNotAllowed {
            get {
                return ResourceManager.GetString("Accounts.EditRoleNotAllowed", resourceCulture);
            }
        }
    }
}
