<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ScopedCssEnabled>false</ScopedCssEnabled>
    <NeutralLanguage>de-DE</NeutralLanguage>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <DisableBuildCompression>true</DisableBuildCompression>
    <StaticWebAssetsEnabled>false</StaticWebAssetsEnabled>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1701;1702;CA2254</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>1701;1702;CA2254</NoWarn>
    <DebugSymbols>false</DebugSymbols>
    <DebugType>None</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Email\EmailTemplate.html" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Email\EmailTemplate.html" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Linkernizer" Version="1.0.1" />
    <PackageReference Include="MailKit" Version="4.13.0" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="9.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL.NetTopologySuite" Version="9.0.4" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.6.7" />
    <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.11" />
    <PackageReference Include="Sqids" Version="3.1.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\PostCodes.Designer.cs">
      <DependentUpon>PostCodes.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Properties\Categories.Designer.cs">
      <DependentUpon>Categories.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Properties\Texts.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Texts.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\SystemTexts.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>SystemTexts.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\PostCodes.resx">
      <LastGenOutput>PostCodes.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Properties\Categories.resx">
      <LastGenOutput>Categories.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Properties\Texts.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Texts.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Properties\SystemTexts.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>SystemTexts.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <Choose>
    <When Condition="'$(Configuration)' == 'Release'">
      <ItemGroup>
        <Content Remove="appsettings.Development.json" />
      </ItemGroup>
    </When>
  </Choose>

</Project>
