name: Cypress build

on:
  push:
    branches: [ main ]
    paths:
      - .github
      - ansible

  workflow_dispatch:

jobs:
  build-docker-image-in-which-the-app-runs-during-Cypress-tests:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Login into Container Registry ghcr.io
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate Dockerfile
        run: .github/make_dockerfile.sh
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}
