name: Run Linters

on:
  push:
    branches: [ main ]

  workflow_dispatch:

defaults:
  run:
    working-directory: gruenes-brett/

jobs:
  stylelint:
    name: stylelint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install modules
        run: npm install

      - name: Run stylelint
        run: npx stylelint *.css

  phpcs:
    name: PHPCS
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"

      - name: Run Composer install
        run: composer install

      - name: Run PHPCS
        run: ./vendor/bin/phpcs 404.php addevent.php calendar.php categories.php explore.php feed.php feeds.php footer.php functions.php ical.php index.php sidebar-administration.php sidebar-calendar.php sidebar-explore.php sidebar.php data/*.php
